apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka-broker
  name: kafka-broker
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
    nodePort: 30005
  selector:
    service: kafka-broker
  type: NodePort
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kafka-broker
  name: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafka-broker
  template:
    metadata:
      labels:
        service: kafka-broker
    spec:
      containers:
      - image: bitnami/kafka:latest
        name: kafka-broker
        imagePullPolicy: Always
        env:
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: "zookeeper-server.default.svc.cluster.local:2181"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-broker.default.svc.cluster.local:9092"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: "enable.zookeeper"
          value: "true"
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "256m"
      restartPolicy: Always
